language: minimal

services:
  - docker

before_install:
  - cd cx-server
  - chmod +x ./cx-server
  - ./cx-server update script || echo "Could not be updated"
  - ./cx-server help
  - ./cx-server start

script: docker ps